
# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: NT.IPTV.NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build  
      
    - name: Test
      run: dotnet test  


    - name: Publish .NET
      run: |
        dotnet publish /p:PublishProfile=Release-win-x86 -c Release
        dotnet publish /p:PublishProfile=Release-win-x64 -c Release

    - name: Upload Published Artifact
      uses: actions/upload-artifact@v2
      with:
        name: NT.IPTV
        path: | 
         ${{ github.workspace }}\NT.IPTV\win-x86
         ${{ github.workspace }}\NT.IPTV\win-x64

   
